export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_POKEDETAILS = "GET_POKEDETAILS";
export const GET_TYPES = "GET_TYPES";
export const CLEAN_POKEMONS = "CLEAN_POKEMONS";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
